LOAD DATA 
APPEND
INTO TABLE MECAPROTEC.MECA_DATALOG 
FIELDS TERMINATED BY ';' 
TRAILING NULLCOLS
(
MDLOG_DATE DATE(20) "YYYY-MM-DD HH24:MI:SS" ,
FIELD1 FILLER,
MDLOG_MACHINE "RTRIM(:MDLOG_MACHINE)" ,
MDLOG_TEMPERATURE,
MDLOG_HUMIDITE
)
